### ISSUE TITLE
checklist

### ISSUE THREAD

**Issue by amstocker** [amstocker/python-ipfs-tools#1]
- blockchain
  - [ ] figure out best way to coordinate blockchain
  - [ ] spec
- index
  - [ ] local or distributed?
  - [ ] what kind of index?
- other
  - [ ] finish multiaddr
    - [ ] unit tests for 2.6, 2.7, 3.3, 3.4
